### ISSUE TITLE
Some Issue in API

### ISSUE THREAD

**Issue by Vijaykv5** [arvindpndit/TubeLight-Video-Streaming-App#5]
Not Sure Why , When I cloned the Repo. its showing this Error.

<img width="1432" alt="Screenshot 2023-09-01 at 1 55 57 PM" src="https://github.com/arvindpndit/TubeLight-Video-Streaming-App/assets/94985341/18734a24-dd53-4228-ae2e-afa14350ab21">

**Comment by arvindpndit** [comment]
make .env file and put the YouTube key there

REACT_APP_API_KEY = "youtube_api_key "
